### ISSUE TITLE
Implement support for Lutris

### ISSUE THREAD

**Issue by Root-Core** [mtkennerly/ludusavi#164]
### What's your idea?

Hello there!

I installed a game (Yooka-Laylee) via Lutris (Flatpak) from Amazon Prime Gaming on the Steam Deck. I noticed that my save files are not recognized. After some research it is clear that Ludusavi knows the game in it's manifest, but does not understand the folder structure generated by Lutris. This might be related with #156.

If I add the prefixes folder and mark it as a prefix folder, it works:
`/home/deck/Games/amazon/yooka-laylee/`

The full save game folder is
`/home/deck/Games/amazon/yooka-laylee/drive_c/users/deck/AppData/LocalLow/Playtonic Ltd/Yooka-Laylee/`

PCGW's data set knows about the correct path on windows:
`%USERPROFILE%\AppData\LocalLow\Playtonic Ltd\Yooka-Laylee\`

There are - as always - several ways to archive this. One would be to check a "Lutris" folder (`$HOME/Games`) with globs.
One more elegant way could be to parse the `*.yml` files that are created for each game in the Lutris config folder:
`/home/deck/.var/app/net.lutris.Lutris/config/lutris/games/`

An excerpt of the file for this specific game:

```yaml
game:
  args: ''
  exe: /home/deck/Games/amazon/yooka-laylee/drive_c/game/YookaLaylee64.exe
  prefix: /home/deck/Games/amazon/yooka-laylee
  working_dir: /home/deck/Games/amazon/yooka-laylee/drive_c/game
```

One could detect all games by adding all `game.prefix`-paths as `prefix`-folder-type roots.
I don't know you philosophy of handling this stuff. This is just a quick and dirty implementation idea, as I just stumbled across this project minutes ago.

**Comment by mtkennerly** [comment]
Hi! Thanks for this suggestion and for the additional details.

I'm open to integrating Lutris via the YAML files, but the main challenge will be identifying the correct file for each game. Do you know where Lutris stores the game's official title, as opposed to the Lutris slug? In this case, the title and slug would be almost the same (`Yooka-Laylee` vs `yooka-laylee`), but that's not always true, since it looks like non-ASCII characters are omitted or even [replaced by a UUID](https://github.com/lutris/lutris/issues/2932).

**Comment by mtkennerly** [comment]
From [this comment](https://forums.lutris.net/t/where-is-lutris-library-data-stored/6739/2), it sounds like the game titles would be stored in `/home/deck/.var/app/net.lutris.Lutris/config/lutris/pga.db`. I'm not sure what else is stored there or if you'd be comfortable sharing a copy of it so I can take a look at the structure. If not, I can try to set up Lutris in a Linux VM to get a copy.

**Comment by Root-Core** [comment]
It is also in the yaml.
I have shortened out the download and install stuff.

```yaml
game:
  args: ''
  exe: /home/deck/Games/amazon/yooka-laylee/drive_c/game/YookaLaylee64.exe
  prefix: /home/deck/Games/amazon/yooka-laylee
  working_dir: /home/deck/Games/amazon/yooka-laylee/drive_c/game
game_slug: yooka-laylee
name: Yooka-Laylee
requires: null
script:
  files:

  [...]

  game:
    args: ''
    exe: $GAMEDIR/drive_c/game/YookaLaylee64.exe
    prefix: $GAMEDIR
    working_dir: $GAMEDIR/drive_c/game
  installer:
  - task:
      arch: win64
      prefix: /home/deck/Games/amazon/yooka-laylee
      wine_path: /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine
  - mkdir: $GAMEDIR/drive_c/game

  [...]  

  - move:

  [...]

  system: {}
  wine:
    version: lutris-7.2-2-x86_64
service: amazon
service_id: ...
slug: yooka-laylee
system: {}
variables: {}
version: Amazon Prime Gaming
wine:
  version: lutris-7.2-2-x86_64
year: null
```

**Comment by mtkennerly** [comment]
Thanks! That's perfect. It looks like this can work pretty similarly to the Heroic integration. I really appreciate all the detail you've provided.

**Comment by Root-Core** [comment]
No problem, thank you for your hard work. I might try to implement it myself, as I wanted to look into Rust anyways.

I'm just a bit unsure about the "correct" way to handle the "roots", as Lutris creates one Wine prefix per game. Would you add all roots found in the *.yml files or just the `$HOME/.var/app/net.lutris.Lutris/config/lutris/games/` folder as a root typed "Lutris"? And how would the restore process work?

I haven't really used Ludusavi yet, tbh.

**Comment by mtkennerly** [comment]
Just the path to the `games` folder as a new Lutris root type. The problem with adding each prefix as its own root is that each prefix has to be checked for each game, which increases scan time exponentially. By having a single root and then only looking up the prefix matching the game, it can stay much more efficient.

The restore process doesn't know about roots. It just knows that the backup found a file at some path, and so it'll copy the data back to the exact same path (notwithstanding any configured redirects).

> I might try to implement it myself, as I wanted to look into Rust anyways.

That would be great, if you're interested :) You could use `src/heroic.rs` as a basis for a new `src/lutris.rs`:

* `lutris::Lutris::scan` would read the YAML files and store any necessary metadata, like the prefix paths
* `lutris::Lutris::scan` would be used by `gui::app::start_backup` and `cli::run`, then passed into `prelude::scan_game_for_backup` so it can check the prefix
* The new root type would be added to `manifest::Store`, and any default paths (e.g., `~/.var/app/net.lutris.Lutris/config/lutris/games`) would be added to `config::find_missing_roots`

**Comment by Root-Core** [comment]
Yeah, I looked into it yesterday and I already implemented some stuff.
Root folder resolution works so far and functions as intended in the GUI.. this was a quick patch.
Sorry for not replying earlier, so your answer could have been less detailed.

I add the Lutris folder as root and try to read all `*.yml` files in a similar fashion to the Heroic Launcher. This still needs some work, but most of the logic is implemented.. I just have to get my head around some Rust specifics, never worked with it.

> The restore process doesn't know about roots and so wouldn't need to change. It just knows that the backup found a file at some path, and so it'll copy the data back to the exact same path (notwithstanding any configured redirects).

Ah okay, I guess that's what #156 is about.

**Comment by mtkennerly** [comment]
> Sorry for not replying earlier, so your answer could have been less detailed.

No worries! Glad to hear it's going well so far.

> EDIT: Lutris is only interesting for Linux.. so should it still be an option for other OSs?

It's an edge case, but I'm gonna say yes because I see some articles/videos about installing Lutris on Windows via WSL. I could also imagine a use case like if you have a full OS backup from a Linux system on an external hard drive and you want to extract just the game saves from it, then you could do that process on any OS.

**Comment by Root-Core** [comment]
The YAML for Amazon Games do provide a field for the games name, but I got some (older?) files on my pc that do not.
For example Uplay (Ubisoft Connect) does not for my installment of Far Cry 6.
There is only an id provided as launch argument. (`7c193df7-ac6c-48ed-ba63-af6f012880a3` in this case.)

```yaml
game:
  args: uplay://launch/7c193df7-ac6c-48ed-ba63-af6f012880a3
  exe: drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/UbisoftConnect.exe
  prefix: /home/aede/Games/ubisoft-connect
system: {}
wine:
  version: lutris-7.2-2-x86_64
```
(This is the full file..)

I'm not sure, if PCGW holds this information.. but I do not think so.
This could help to recue some of the older entries savegames.

It seems a freshly installed game does provide the name in the YAML for Uplay.
I will install some additional games on different platforms for testing later.. I do not use Lutris that often. I just thought it would be cool, if it was supported here.

-------

On the progress: Roots are detected and files get parsed and the official titles are found.. so everything should work out for the supported, newer files. Still need to actually test it though.
