### ISSUE TITLE
Heroic Detection still not working on flathub on Steam Deck

### ISSUE THREAD

**Issue by jimbojd72** [mtkennerly/ludusavi#186]
### Ludusavi version

v0.15.2

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

I know it is supposed to worked based on https://github.com/mtkennerly/ludusavi/pull/141

Configuring /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic root manually doesn't find anything

I put pictures of my configurations and an samples of the games I have installed just in case.

### Logs

![image](https://user-images.githubusercontent.com/29709551/222775727-9fbf4570-d7c1-4902-80e2-36a7511f1fa3.png)
![image](https://user-images.githubusercontent.com/29709551/222775998-0de95fbf-32d3-48b3-9f48-114e283ad07d.png)

**Comment by jimbojd72** [comment]
[ludusavi_rCURRENT.log](https://github.com/mtkennerly/ludusavi/files/10884410/ludusavi_rCURRENT.log)

config.yaml
```
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: ~
language: en-US
theme: dark
roots:
  - path: /home/deck/.local/share/Steam
    store: steam
  - path: /run/media/mmcblk0p1
    store: steam
  - path: /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic
    store: heroic
redirects: []
backup:
  path: /home/deck/ludusavi-backup
  ignoredGames: []
  merge: true
  filter:
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 2
  format:
    chosen: zip
    zip:
      compression: zstd
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/deck/ludusavi-backup
  ignoredGames: []
  sort:
    key: name
    reversed: false
customGames: []

```

**Comment by mtkennerly** [comment]
Thanks for the detailed report!

Of those four games, PCGW doesn't have any info for Demon Turf save data, but the other three should work. I see that FTL and Loop Hero have native Linux versions (I'm assuming Heroic would install these instead of the Windows versions), and FIST only has a Windows version available.

Could you double check a few things?

* For FTL, does this folder exist? `/home/deck/.var/app/com.heroicgameslauncher.hgl/data/FasterThanLight`
* For FIST, there should be a corresponding JSON file In `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig`. What's the `winePrefix` setting in that file?
* Inside of FIST's `winePrefix` folder, there should be these subfolders: `users/*/AppData/Local/ZingangGame/Saved/SaveGames` (where `*` is any username). Does that exist?

**Comment by jimbojd72** [comment]
I don't think this is a game specific issue but a Heroic parser issue. But with your question I was able to dig deeper

I look into `/home/deck/.var/app/com.heroicgameslauncher.hgl/data` like suggested but there is almost nothing:

```
(130)(deck@steamdeck ~)$ ls /home/deck/.var/app/com.heroicgameslauncher.hgl/data/FasterThanLight
ls: cannot access '/home/deck/.var/app/com.heroicgameslauncher.hgl/data/FasterThanLight': No such file or directory
(2)(deck@steamdeck ~)$ ls /home/deck/.var/app/com.heroicgameslauncher.hgl/data/
applications  Steam
(deck@steamdeck ~)$ ls /home/deck/.var/app/com.heroicgameslauncher.hgl/data/applications/
(2)(deck@steamdeck ~)$ ls /home/deck/.var/app/com.heroicgameslauncher.hgl/data/Steam
```

I noticed my games are in fact in `/home/deck/Games/Heroic` and prefixed in `/home/deck/Games/Heroic/Prefixes`

```
(deck@steamdeck ~)$ ls /home/deck/Games/Heroic
 AxiomVerge2    EnterTheGungeon   Flashback                 HeroicBashLauncher-2.9.2   LoopHero        Prefixes      TheEndIsNigh
 DemonTurf      FasterThanLight  'Greak Memories of Azur'   InscryptionWkwPQ           NuclearThrone   RogueLegacy   VigilTheLongestNight
 DiscoElysium   FIST              Hades                     IntoTheBreach              Postal         'Samorost 1'
(deck@steamdeck ~)$ ls /home/deck/Games/Heroic/Prefixes/
 AxiomVerge2   DiscoElysium         FasterThanLight                    Hades             'Into The Breach'   LoopHero
'Demon Turf'   EnterTheGungeon     'F.I.S.T. Forged In Shadow Torch'   Inscryption        IntoTheBreach      NuclearThrone
 DemonTurf    'Faster Than Light'  'Greak Memories of Azur'            InscryptionWkwPQ  'Loop Hero'         TheEndIsNigh
```

But path `/home/deck/Games/Heroic`  should be discoverable from heroic config file for ludusavi to find as you can see below:

```
(deck@steamdeck heroic)$ cat /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/config.json
{
  "defaultSettings": {
    "checkUpdatesInterval": 10,
    "enableUpdates": false,
    "addDesktopShortcuts": false,
    "addStartMenuShortcuts": false,
    "autoInstallDxvk": false,
    "autoInstallVkd3d": false,
    "addSteamShortcuts": true,
    "preferSystemLibs": false,
    "checkForUpdatesOnStartup": false,
    "autoUpdateGames": false,
    "customWinePaths": [],
    "defaultInstallPath": "/home/deck/Games/Heroic",   <<<<---------- Interesting path to parse
    "libraryTopSection": "recently_played_installed",
    "defaultSteamPath": "/home/deck/.steam/steam",
    "defaultWinePrefix": "/home/deck/Games/Heroic/Prefixes", <<<<---------- Interesting path to parse
    "hideChangelogsOnStartup": false,
    "language": "en",
    "maxWorkers": 0,
    "minimizeOnLaunch": false,
    "nvidiaPrime": false,
    "enviromentOptions": [],
    "wrapperOptions": [],
    "showFps": false,
    "useGameMode": false,
    "userInfo": {
      "epicId": "a5a09135dee444b3a25747cc694d2e3d",
      "name": "deck"
    },
    "wineCrossoverBottle": "Heroic",
    "winePrefix": "/home/deck/.wine",
    "wineVersion": {
      "bin": "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton",
      "name": "Proton - Proton 7.0",
      "type": "proton"
    },
    "altLegendaryBin": "",
    "altGogdlBin": "",
    "disableController": false,
    "egsLinkedPath": "",
    "maxRecentGames": 5,
    "showUnrealMarket": false,
    "eacRuntime": false,
    "battlEyeRuntime": false
  },
  "version": "v0"
}
```

Long story short: I guess ludusavi should get the default paths from `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/config.json` and add those to the roots to backup.

**Comment by mtkennerly** [comment]
There should be some game-specific config files that identify which prefix belongs to each game. That's what Ludusavi looks for right now, so I'd like to figure out why that part isn't working. What do you see in `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig` ? Could you share some of the files from that folder, particularly for FTL and FIST?

**Comment by jimbojd72** [comment]
No idea what is the naming scheme of those files, but with some grep I found:

```
(deck@steamdeck GamesConfig)$ cat /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/bf4808b3395b43fb80afbe6773e1661f.json
{
  "bf4808b3395b43fb80afbe6773e1661f": {
    "autoInstallDxvk": false,
    "autoInstallVkd3d": false,
    "preferSystemLibs": false,
    "nvidiaPrime": false,
    "enviromentOptions": [],
    "wrapperOptions": [],
    "showFps": false,
    "useGameMode": false,
    "language": "",
    "wineVersion": {
      "bin": "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton",
      "name": "Proton - Proton 7.0",
      "type": "proton"
    },
    "winePrefix": "/home/deck/Games/Heroic/Prefixes/F.I.S.T. Forged In Shadow Torch"
  },
  "version": "v0",
  "explicit": true
}
```
FTL:

```
(deck@steamdeck GamesConfig)$ cat /home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Blowfish.json 
{
  "Blowfish": {
    "autoInstallDxvk": false,
    "autoInstallVkd3d": false,
    "preferSystemLibs": false,
    "maxSharpness": 2,
    "nvidiaPrime": false,
    "enviromentOptions": [],
    "wrapperOptions": [],
    "savesPath": "",
    "showFps": false,
    "targetExe": "",
    "useGameMode": false,
    "language": "",
    "wineVersion": {
      "bin": "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton",
      "name": "Proton - Proton 7.0",
      "type": "proton"
    },
    "winePrefix": "/home/deck/Games/Heroic/Prefixes/Faster Than Light",
    "eacRuntime": false,
    "battlEyeRuntime": false,
    "gogSaves": [],
    "wineCrossoverBottle": ""
  },
  "version": "v0",
  "explicit": true
}
```

**Comment by mtkennerly** [comment]
Yeah, the naming is usually weird 😅 Thanks, the contents there look normal.

Would you mind giving me the log for this command for some extra details?

```
flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "
FTL: Faster Than Light"
```

Here's what Ludusavi does for Epic games (I'll use `${heroic}` as an abbreviation for `/home/deck/.var/app/com.heroicgameslauncher.hgl`):

* Check `${heroic}/config/legendary` and/or `~/.config/legendary` for a file named `installed.json`.
  * From that file, record each game's `app_name` and `title`.
* Check `${heroic}/config/heroic/GamesConfig` for a JSON file with the same `app_name` from the above step.
  * From that file, record the game's `wine_prefix`.
* Finally, the `title` needs to match the PCGamingWiki article name, and then Ludusavi can connect the game to its prefix.

If that works, then the next question is whether the saves exist where Ludusavi expects. For FTL, based on your `Blowfish.json`, that would be:

* `/home/deck/Games/Heroic/Prefixes/Faster Than Light/users/*/Documents/My Games/FasterThanLight`

Does that exist?

**Comment by jimbojd72** [comment]
> Would you mind giving me the log for this command for some extra details?

Not a lot here:

```
(2)(deck@steamdeck ~)$ flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "FTL: Faster Than Light"

Overall:
  Games: 0
  Size: 0 B
  Location: /home/deck/ludusavi-backup
```

> /home/deck/Games/Heroic/Prefixes/Faster Than Light/drive_*/users/*/Documents/My Games/FasterThanLight
```
(2)(deck@steamdeck ~)$ ls /home/deck/Games/Heroic/Prefixes/Faster\ Than\ Light/
config_info  pfx  pfx.lock  tracked_files  version
```

There is a missing `pfx` directory in your path above. But I could find the saves under this path instead:
```
(deck@steamdeck ~)$ ls /home/deck/Games/Heroic/Prefixes/Faster\ Than\ Light/pfx/drive_c/users/steamuser/Documents/My\ Games/FasterThanLight/
ae_prof.sav  continue.sav
```
