### ISSUE TITLE
`<path-to-game>` in Wine prefix / Lutris?

### ISSUE THREAD

**Issue by eskay993** [mtkennerly/ludusavi#223]
### What's your question?

Hi

I saw you other reply to a similar query about how PCGamingWiki's `<path-to-game>` is handled  in Windows, which makes sense, but  I have a query about how  it works in Wine / Lutris.

If I set my Lutris root as `~/.config/lutris`, and I have a game instated in say:

`/data/games/silent-hill-3/drive_c/Program Files/KONAMI/SILENT HILL 3`

Then would Ludusavi resolve `<path-to-game>` in this instance?  It's not for me, but not sure if it's supposed to.

If it does not currently do that, in theory it should be possible to extract it from the Lutris game yaml by looking at `exe` and `prefix`, for example:

```
game:
  arch: win32
  exe: drive_c/Program Files/KONAMI/SILENT HILL 3/sh3.exe
  prefix: /data/games/silent-hill-3
game_slug: silent-hill-3
name: Silent Hill 3
```

Is this something you would consider? Appreciate this would be much trickier with a `Wine prefix` root if the game is installed in the prefix, but hopefully possible with a `Lutris` root.

Thanks for your help.

Loving the app by the way! Saved my bacon more than once :)
