### ISSUE TITLE
Lutris Itch.io support

### ISSUE THREAD

**Issue by kekonn** [mtkennerly/ludusavi#237]
### What's your idea?

Lutris has added itch.io support, but I see that these games are not appearing in Ludusavi. I assume we scan the Lutris database or config file for installed games, so perhaps this is just a filtering issue?

**Comment by mtkennerly** [comment]
Hi! Could you give me a sample of the YAML file for one of these games? Ludusavi expects it to have the `name` field and either the `game.working_dir` or `game.exe` fields.

**Comment by kekonn** [comment]
```yaml
game:
  exe: /home/kekkon/Games/itchio/mewnbase/MewnBase
game_slug: mewnbase
linux: {}
name: MewnBase
requires: null
script:
  files:
  - itchupload: N/A:Select the installer from itch.io
  game:
    exe: _xXx_AUTO_ELF_xXx_
  installer:
  - extract:
      dst: $CACHE
      file: itchupload
  - merge:
      dst: $GAMEDIR
      src: $CACHE
  - write_json:
      data:
        appid: '51221'
        build: '656231'
        date: 1686473591
        runner: linux
        service: itchio
        slug: mewnbase
        upload: '355694'
      file: $GAMEDIR/.lutrisgame.json
      merge: false
service: itchio
service_id: '51221'
slug: mewnbase
system: {}
variables: {}
version: itch.io
year: null
```

This is the yaml for Mewnbase
