### ISSUE TITLE
Create a Snap package for Linux

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#24]
I've made a few unsuccessful attempts at this. Not really sure how to proceed.

### snapcraft.yaml
```yaml
name: ludusavi
base: core18
version: '0.1'
summary: Backup tool for video game save data
description: |
  Test.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  executable:
    source: https://github.com/mtkennerly/ludusavi/releases/download/v0.5.0/ludusavi-v0.5.0-linux.zip
    # source: target/release/
    plugin: dump
    prime:
      - ludusavi
    override-build: |
      chmod +x ludusavi
      snapcraftctl build
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libx11-6
      - libxcursor1
      - libxrandr2
      - libxi6
      - libx11-xcb1

apps:
  ludusavi:
    command: ludusavi
    environment:
      LD_LIBRARY_PATH: /root/stage/usr/lib/x86_64-linux-gnu
```

### Output
```
$ snapcraft && snap install --dangerous --devmode ludusavi_0.1_amd64.snap && ludusavi
Launching a VM.
[...]
ludusavi 0.1 installed
/snap/ludusavi/x17/ludusavi: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or directory

$ snapcraft --shell-after
$ LD_LIBRARY_PATH=/root/stage/usr/lib/x86_64-linux-gnu ./prime/ludusavi
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### snapcraft.yaml
```yaml
name: ludusavi
base: core18
version: '0.1'
summary: Backup tool for video game save data
description: |
  Test.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  executable:
    source: https://github.com/mtkennerly/ludusavi/releases/download/v0.5.0/ludusavi-v0.5.0-linux.zip
    # source: target/release/
    plugin: dump
    prime:
      - ludusavi
    override-build: |
      chmod +x ludusavi
      snapcraftctl build
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libx11-6
      - libxcursor1
      - libxrandr2
      - libxi6
      - libx11-xcb1

  desktop-helper:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    plugin: dump
    prime:
      - desktop-launch
    override-build: |
      echo '#!/bin/bash' > desktop-launch
      cat common/init >> desktop-launch
      cat common/desktop-exports >> desktop-launch
      cat common/mark-and-exec >> desktop-launch
      chmod +x desktop-launch
      snapcraftctl build

apps:
  ludusavi:
    command: desktop-launch ludusavi
    environment:
      LD_LIBRARY_PATH: /root/stage/usr/lib/x86_64-linux-gnu
```

### Output
```
$ snapcraft && snap install --dangerous --devmode ludusavi_0.1_amd64.snap && ludusavi
Launching a VM.
[...]
ludusavi 0.1 installed
/snap/ludusavi/x19/desktop-launch: line 536: exec: ludusavi: not found
```
