### ISSUE TITLE
Option to only back up saves confirmed for your OS

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#30]
The data set indicates whether a save location has been confirmed for a particular OS and store, but right now Ludusavi backs up everything regardless, since it's generally safer to back up too much than too little. That's good for Linux and Mac users, since some games may only have confirmed locations for Windows even though it's the same on any OS, but it's not so good for Windows users since they typically won't gain anything from the extra Linux/Mac locations (and those locations may not be as refined as the Windows data, leading to extraneous files like game assets).

This will just be a global setting. I don't think it's appropriate to set for individual games - for that use case, I would rather introduce a concept of ignored paths (although the ideal solution there would be to refine the data set so that no one would have a desire to ignore specific files in the first place).

It may be worth adding a similar filter for store type, but I doubt that there would be many store-specific false positives. For example, even if we happen to check a Steam subdirectory (like `userdata/<id>`) in an Epic root, it just won't find anything, rather than finding something irrelevant. I'm not opposed to adding that, but I'd like to wait for a confirmed use case.

**Comment by darklinkpower** [comment]
Question regarding this: when having this setting enabled on Windows, would it also backup what is marked as "Steam" too? Since "Steam" refers to the Windows version of it too and also certain games store saves in the two locations or sometimes even just the Steam location is used in the game.

![imagen](https://user-images.githubusercontent.com/1389286/89106288-4f0ab380-d3ee-11ea-9743-8e784915731a.png)

**Comment by mtkennerly** [comment]
Yeah. saves marked for Steam would still be included, regardless of this setting. The data in that screenshot is mapped into the manifest like this (omitting some other data for clarity):

```yaml
Dying Light:
  files:
    <base>/DW/out/Settings:
      when:
        - os: linux
    <root>/userdata/<storeUserId>/239140/remote/out:
      when:
        - store: steam
    <winDocuments>/DyingLight/out/save:
      when:
        - os: windows
    <winDocuments>/DyingLight/out/settings:
      when:
        - os: windows
```

So basically this option would mean excluding any paths with `os: windows`, but won't have an effect on entries with `store: steam`. That's what I meant about "a similar filter for store type".

**Comment by mtkennerly** [comment]
> ![image](https://user-images.githubusercontent.com/4934192/89109683-68712700-d411-11ea-9b6b-c169484af4e9.png)

For example, let's say you're on Windows and you're backing up this game:

```yaml
Example Game:
  files:
    a:
      when:
        - os: windows
    b:
      when:
        - os: linux
    c:
      when:
        - store: steam
    d:
      when:
        - store: steam
        - os: linux
    e:
      when:
        - store: steam
          os: linux
    f: {}
```

In the backup:

* A is included, because there is specifically an `os: windows` constraint.
* B is excluded, because there are `os:` constraints and none of them are for Windows.
* C is included, because there are no `os:` constraints.
* D is included, because one constraint (`store: steam`) does not specify `os:` - i.e., this save location is for Steam OR Linux.
* E is excluded, because it has a single constraint for Steam AND Linux together.
* F is included, because it has no constraints.
