### ISSUE TITLE
Cult of the Lamb 1.3.3.206 not recognized

### ISSUE THREAD

**Issue by mainrs** [mtkennerly/ludusavi#309]
### Ludusavi version

v0.22.0

### Operating system

Linux

### Installation method

Flatpak

### Description

I own the Game on GOG and used Lutris (specifically the autoinstaller) to install it. The lutris config folder contains a yml file for the game. But ludusavi does not pick it up. 

If you need more information, let me know.

### Files

Lutris game file under the `.config/lutris/games` folder.
```yaml
game:
  exe: /home/john/Games/gog/cult-of-the-lamb/drive_c/GOG Games/Cult of the Lamb/Cult
    Of The Lamb.exe
  launch_configs: []
  name: Cult of the Lamb
game_slug: cult-of-the-lamb
name: Cult of the Lamb
requires: null
script:
  files:
  - goginstaller: N/A:Select the installer from GOG
  game:
    exe: /home/john/Games/gog/cult-of-the-lamb/drive_c/GOG Games/Cult of the Lamb/Cult
      Of The Lamb.exe
    launch_configs: []
    name: Cult of the Lamb
  installer:
  - autosetup_gog_game: goginstaller
  system: {}
service: gog
service_id: '2034949552'
slug: cult_of_the_lamb
system: {}
variables: {}
version: GOG (auto-generated)
wine: {}
year: null

```
