### ISSUE TITLE
Ludusavi tries to back up my entire %userprofile%

### ISSUE THREAD

**Issue by j-dec** [mtkennerly/ludusavi#36]
Using the GUI, Ludusavi tries to backup many GB worth of files it identifies as "Battlefield II"'s save data (a game I've never had on my PC). The GUI crashes after it tries to display the list of those files. After following through with the backup, it turns out the files are actually the entirety of my %userprofile%.

This doesn't happen if the CLI is used instead of the GUI.

**Comment by mtkennerly** [comment]
Thank you for reporting this. The save path for Battlefield 2 is malformed and I could see that causing an issue (I'll try to get it fixed on PCGamingWiki), but I'm not able to reproduce this issue using the latest version of Ludusavi. Some questions for you:

* What version of Ludusavi are you using?
* Are you on Windows 10?
* Just to be sure, does it really say `Battlefield II` or is it `Battlefield 2`?

**Comment by j-dec** [comment]
* v0.7.0
* Yes.
* It's actually Battlefield 2, sorry.
* I used a freshly installed Ludusavi. Here's the whole file:
```
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"d012ef512df925a0c3f71a1abbdb85d84c656bc5750c3748b75fa0c52fef6fd3\""
roots:
  - path: "C:\\Program Files (x86)/Steam"
    store: steam
backup:
  path: "F:\\Portable Software\\ludusavi-win64\\ludusavi-backup"
  ignoredGames: []
  merge: true
  filter: {}
restore:
  path: "F:\\Portable Software\\ludusavi-win64\\ludusavi-backup"
  ignoredGames: []
  redirects: []
customGames: []
```

**Comment by mtkennerly** [comment]
The wiki was updated to fix the bad path, so I've updated Ludusavi's data set as well. Could you reopen Ludusavi and see if the issue is fixed?

For some reason, even with your exact config, I couldn't reproduce the issue, so I'll still need to try to figure out what the difference is there.

**Comment by j-dec** [comment]
The issue is still present.

**Comment by j-dec** [comment]
The issue is no longer present after editing the manifest.yaml file in `%userprofile%\.config\ludusavi\` manually.

**Comment by mtkennerly** [comment]
Ah, sorry, it looks like I hit an error when trying to push the data update, and it didn't actually go through. It should update properly the next time you open Ludusavi now.

**Comment by j-dec** [comment]
Yup, Ludusavi recreated the file now (it didn't even launch previously). Issue no longer present.

**Comment by mtkennerly** [comment]
Great! I'll try to add some more safeguards in the importer script to handle bad paths like that before they make it into the manifest.

As far as why it behaved differently on our systems and why you got different results from the GUI and CLI, would you be willing to try a custom version of Ludusavi with some diagnostic info? (No worries if you'd rather not.)

**Comment by j-dec** [comment]
Sure.

**Comment by mtkennerly** [comment]
Thanks! Here it is (Windows 64-bit):

[ludusavi-issue-36-test-1.zip](https://github.com/mtkennerly/ludusavi/files/5046304/ludusavi-issue-36-test-1.zip)

This build will create a `%USERPROFILE%\.config\ludusavi\log` folder with some log files (it adds a new one each time you run it). It's set up to only log activity for `Battlefield 2` in particular.

For the test, please also replace the `customGames: []` line in config.yaml with this, in order to override the path for Battlefield 2 back to the bad version:

```yaml
customGames:
  - name: Battlefield 2
    files:
      - "<winDocuments>/Battlefield 2/Profiles/<home>"
    registry: []
```

Then just try the same things you did in the GUI and CLI before and post the logs here.
