### ISSUE TITLE
Stuck on scanning games

### ISSUE THREAD

**Issue by Smexhy** [mtkennerly/ludusavi#375]
### Ludusavi version

v0.24.3

### Operating system

Windows

### Installation method

Standalone

### Description

Hi, I am being stuck on scanning the last game, tried to wait for multiple minutes and restart client as well without success. Launching the program with privilages as well. No error / warn logs. I would be interested in getting the debug logs manually if you tell me how to use the enviroment variables to enable it for ludasvi, as I didn't get that part in your documentation.

When I hit cancel button, that goes into being stuck as well, and I have to close the whole app to be able to do anything beyond that.

![image](https://github.com/user-attachments/assets/243ea398-f999-4231-9fc4-9bda5b5b68ef)

### Logs

```
---
runtime:
  threads: ~
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
language: en-US
theme: dark
roots:
  - store: steam
    path: "C:/Program Files (x86)/Steam"
  - store: uplay
    path: "C:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher"
  - store: microsoft
    path: "C:/Program Files/WindowsApps"
  - store: ea
    path: "C:/Program Files/EA Games"
  - store: steam
    path: "D:/SteamLibrary"
redirects: []
backup:
  path: "C:\\Users\\user/ludusavi-backup"
  ignoredGames:
    - Animal Well
    - Battlefield 2042
    - Crash Bandicoot N. Sane Trilogy
    - DayZ
    - Dead by Daylight
    - Diablo IV
    - Doom Eternal
    - Euro Truck Simulator 2
    - Forza Horizon 5
    - Golf with Your Friends
    - Grand Theft Auto V
    - House of Ashes
    - Lethal Company
    - Medieval Dynasty
    - "Minecraft: Bedrock Edition"
    - Need for Speed Unbound
    - "No Man's Sky"
    - "Ori and the Blind Forest: Definitive Edition"
    - Overwatch 2
    - "PUBG: Battlegrounds"
    - Red Dead Redemption 2
    - Rocket League
    - Sea of Thieves
    - Slay the Princess
    - Smite
    - Team Fortress 2
    - "The Hunter: Call of the Wild"
    - The Outlast Trials
    - Tomb Raider I-III Remastered
    - TrackMania Nations Forever
    - TrackMania United Forever
    - Trackmania (2020)
    - Wreckfest
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: "C:\\Users\\user/ludusavi-backup"
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: ""
    arguments: "--fast-list --ignore-checksum"
customGames: []

```
