### ISSUE TITLE
Home folder custom path not taking effect

### ISSUE THREAD

**Issue by tekert** [mtkennerly/ludusavi#461]
### Ludusavi version

v0.28.0

### Operating system

Windows

### Installation method

Standalone

### Description

For example for this manifest:

```
Grand Theft Auto V:
  files:
    "<winDocuments>/Rockstar Games/GTA V/Profiles/<storeUserId>":
      tags:
        - save
      when:
        - os: windows
    "<winDocuments>/Rockstar Games/GTA V/settings.xml":
      tags:
        - config
      when:
        - os: windows
    "<winProgramData>/Socialclub/Player":
      tags:
        - save
      when:
        - os: windows
  id:
    lutris: grand-theft-auto-v
    steamExtra:
      - 362003
      - 376850
  installDir:
    Grand Theft Auto V: {}
  launch:
    "<base>/PlayGTAV.exe":
      - when:
          - bit: 64
            os: windows
            store: steam
  steam:
    id: 271590
```

And this custom path:
```
roots:
  - store: otherHome
    path: "G:\\MYCUSTOMDIR\\etc\\Users\\myuser"
```

Before 0.28 (dont remember wich version) this worked, 
`"<winDocuments>/Rockstar Games/GTA V/Profiles/<storeUserId>"`

Would backup  G:\MYCUSTOMDIR\etc\Users\myuser\Rockstar Games\GTA V\Profiles\

Now, it wont scan that dir.

**Comment by mtkennerly** [comment]
Hi! Just to confirm, you wrote `G:\MYCUSTOMDIR\etc\Users\myuser\Rockstar Games\GTA V\Profiles\`, but did you mean `G:\MYCUSTOMDIR\etc\Users\myuser\Documents\Rockstar Games\GTA V\Profiles\` (with a `Documents` folder)?

As a test, please open Command Prompt, run the following commands, and then post a copy of the `%APPDATA%/ludusavi/ludusavi_rCURRENT.log` file:

```
set RUST_LOG=ludusavi=trace
C:\path\to\ludusavi.exe backup --preview "Grand Theft Auto V"
```

(just change `C:\path\to\ludusavi.exe` to the actual path on your system)

**Comment by tekert** [comment]
The `G:\MYCUSTOMDIR\etc\Users\myuser`  is a backup, inside that dir is a home dir structure, like C:\Users\*User* , in previous versions this worked, you could have multiple home dirs.

the `ludusavi.exe backup --preview "Grand Theft Auto V"`
Is trying to delete the save files inside `Rockstar Games\GTA V\Profiles\` from my previous backup.

`G:\MYCUSTOMDIR\etc\Users\myuser` on my personal computer = `G:/Backups/Disco-C-2002-2017/Users/Tekert`

But i have other home dirs with the same problem, for example home dirs that are "moved" by windows to new locations, like C:\Users\*user* to E:\Data\*User*

that's is why i want to concentrate on this old backup home dir, maybe fixing this will fix the other one too, this took me a while to find since it silently did not backup new games correctly (some of them), but when backip up old games, this one in particular showed the problem, Maybe is the way the metadata is parsed? or i dont know.

```
PS C:\Users\Tekert> ludusavi.exe backup --preview "Grand Theft Auto V"
Grand Theft Auto V [2.34 KiB] [Δ]:
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/MISREP0000
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/MISREP0000.bak
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/PGTA51934866888
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50000
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50000.bak
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50001
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50001.bak
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50002.bak
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50015
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/SGTA50015.bak
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/cfg.dat
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/control/user.xml
  - [x] G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/Profiles/DFE3B7FD/pc_settings.bin
  - G:/Backups/Disco-C-2002-2017/Users/Tekert/Documents/Rockstar Games/GTA V/settings.xml

Overall:
  Games: 1 [Δ1]
  Size: 2.34 KiB
  Location: G:/Backups/ludusavi-backup
```
