### ISSUE TITLE
Root path not resolving when set to Network Location or mapped Network Drive

### ISSUE THREAD

**Issue by RespiteFromReality** [mtkennerly/ludusavi#467]
### Ludusavi version

v0.28.0

### Operating system

Windows

### Installation method

Standalone

### Description

When I set a Network Location (`\\192.168.x.x\stuffhere`) or a Mapped Network Drive (`Z:\`) as a Root, it is never correctly resolved when using `<root>` or `<base>`.

Here are the relevant parts in the config.yaml (The IP was intentionally hidden)

```yaml
roots:
  - store: other
    path: "\\\\192.168.X.X\\storage"
  - store: other
    path: "\\\\?\\UNC\\192.168.X.X\\storage"
  - store: other
    path: "Z:\\"
  - store: other
    path: "<home>/Downloads"

customGames:
  - name: test
    integration: override
    files:
      - "<root>/test"
      - "<base>"
    registry: []
    installDir: []
```

Both storage and Downloads folder have a "test" folder with a save.txt in it, only the Downloads one is detected during scan.

I know the drive works, because it scans correctly when set as absolute path (or used as destination path for backup/restore).

Like so:
```yaml
customGames:
  - name: test
    integration: override
    files:
      - "\\\\192.168.X.X\\storage\\test"
    registry: []
    installDir: []
```

Maybe I'm just misunderstanding something somewhere, in which case apologies in advance.

### Logs

No logs were available.
