### ISSUE TITLE
Does not detect saves from Heroic

### ISSUE THREAD

**Issue by pktiuk** [mtkennerly/ludusavi#478]
### Ludusavi version

v0.28.0

### Operating system

Linux (Steam Deck)

### Installation method

Flatpak

### Description

I installed ludusavi on my Steam Deck to get backups from Games I played on my machine. And it missed all of the games I got from Heroic.

I have some games from Heroic installed now (like Mafia definitive Edition) and games I played before, but uninstalled (Death Stranding)

### Logs

![Image](https://github.com/user-attachments/assets/5cc55a7e-fc86-477d-a5fd-4e12c9321511)

[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/19276489/ludusavi_rCURRENT.log)

Interesting part of logs:
```
[2025-03-17T00:11:40.427Z] DEBUG [ludusavi::scan::launchers] Scanning launcher info: Heroic(Heroic { path: StrictPath { raw: "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic", basis: None } })
[2025-03-17T00:11:40.427Z] DEBUG [ludusavi::scan::launchers::legendary] In Legendary source 'StrictPath { raw: "~/.config/legendary/installed.json", basis: None }', unable to read installed.json | Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2025-03-17T00:11:40.427Z] DEBUG [ludusavi::scan::launchers] launcher games found (Heroic(Heroic { path: StrictPath { raw: "/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic", basis: None } })): {
    "Enter the Gungeon": {
        LauncherGame {
            install_dir: Some(
                StrictPath { raw: "/home/deck/Games/Heroic/EnterTheGungeon", basis: None },
            ),
            prefix: None,
            platform: Some(
                Windows,
            ),
        },
    },
    "Mafia: Definitive Edition": {
        LauncherGame {
            install_dir: Some(
                StrictPath { raw: "/home/deck/Games/Heroic/Mafia Definitive Edition", basis: None },
            ),
            prefix: Some(
                StrictPath { raw: "/home/deck/Games/Heroic/Prefixes/Mafia Definitive Edition/pfx", basis: None },
            ),
            platform: Some(
                Windows,
            ),
        },
    },
}
[2025-03-17T00:11:40.427Z] DEBUG [ludusavi::scan::launchers] Scanning launcher info: Steam(Steam { path: StrictPath { raw: "/home/deck/.local/share/Steam", basis: None } })
```

It detected only two games from heroic

And it missed entirely Death Stranding (defined in file `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/GamesConfig/Boga.json` ) 

[Boga.json](https://github.com/user-attachments/files/19276530/Boga.json)

In this case I have a lot of saves

```
(2)(deck@steamdeck ~)$ ls /home/deck/Games/Heroic/Prefixes/Death\ Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c
autosave0   autosave17  autosave5     manualsave12  manualsave20  manualsave9  quicksave15  quicksave3
autosave1   autosave18  autosave6     manualsave13  manualsave21  profile      quicksave16  quicksave4
```

**Comment by mtkennerly** [comment]
Hi! Thanks for reporting this. Couple of things:

* Which stores are the games from? (GOG, Epic, Amazon, sideload)
* Could you please provide the log file for this command?
  * `flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "Enter the Gungeon" "Mafia: Definitive Edition" "Death Stranding"`

**Comment by pktiuk** [comment]
> Which stores are the games from? (GOG, Epic, Amazon, sideload)

I use GOG (Mafia), Epic (Death Stranding), and had some sideloaded games

> Could you please provide the log file for this command

It detected only a copy of Mafia from Steam, not from Heroic

```
(1)(deck@steamdeck ~)$ flatpak run --env=RUST_LOG=ludusavi=trace com.github.mtkennerly.ludusavi backup --preview "Enter the Gungeon" "Mafia: Definitive Edition" "Death Stranding"
Mafia: Definitive Edition [2.25 MiB] [+]:
  - [+] /home/deck/.local/share/Steam/steamapps/compatdata/1030840/pfx/drive_c/users/steamuser/Documents/My Games/Mafia Definitive Edition/Data/76561198066713802/gamesaves/default/aslot/save0.sav
...
  - [+] /home/deck/.local/share/Steam/userdata/106448074/760/remote/1030840/screenshots/20250129212625_1.jpg

Overall:
  Games: 1 [+1]
  Size: 2.25 MiB
  Location: /home/deck/ludusavi-backup
```

**Comment by mtkennerly** [comment]
Could you please provide the `.log` file (not the console output)? The `trace` log level will provide additional detail.

**Comment by pktiuk** [comment]
[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/19291625/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Thanks!

For Mafia, could you check if any of these paths or similar ones exist? Ludusavi is looking for these Heroic paths, but maybe the actual paths are different:

* `/home/deck/Games/Heroic/Mafia Definitive Edition/My Games/Mafia Definitive Edition/Saves/profiles`
* `/home/deck/Games/Heroic/Mafia Definitive Edition/user/Data/Saves/gamesaves`
* `/home/deck/Games/Heroic/Prefixes/Mafia Definitive Edition/pfx/drive_*/users/*/My Documents/My Games/Mafia Definitive Edition/Data/*/gamesaves`
* `/home/deck/Games/Heroic/Prefixes/Mafia Definitive Edition/pfx/drive_*/users/*/Documents/My Games/Mafia Definitive Edition`
* `/home/deck/Games/Heroic/Prefixes/Mafia Definitive Edition/pfx/drive_*/users/*/Documents/My Games/Mafia Definitive Edition/Data/*/gamesaves`
* `/home/deck/Games/Heroic/Prefixes/Mafia Definitive Edition/pfx/drive_*/users/*/My Documents/My Games/Mafia Definitive Edition`

For Death Stranding, can you check if either of these files exists?

* `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/installed.json`
* `/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json`

And if so, can you send me a copy of them? From the logs, it seems like these files don't reference the `Boga` app ID, but I'd like to confirm.

**Comment by pktiuk** [comment]
## Death Stranding

`/home/deck/.var/app/com.heroicgameslauncher.hgl/config/legendary/installed.json`

[installed.json](https://github.com/user-attachments/files/19335539/installed.json) - Death Stranding is not installed, so I don't expect it in this file

`/home/deck/.var/app/com.heroicgameslauncher.hgl/config/heroic/legendaryConfig/legendary/installed.json`

[installed.json](https://github.com/user-attachments/files/19335562/installed.json)

**Comment by pktiuk** [comment]
### Mafia
 
Sorry I made a Mistake in this one. I removed saves, when I was migrating them to Steam (I needed save sync). But I recreated them now.

It appears, that these files are not stored in prefix, but in Documents directory `/home/deck/Documents/My Games/Mafia Definitive Edition/` and now Ludusavi is able to detect them.

It seems that this issue only affected Death Stranding.

**Comment by pktiuk** [comment]
Yes    
[legendary_library.json](https://github.com/user-attachments/files/19377026/legendary_library.json)


> may not be clearly linked to any specific copy of the game, so Ludusavi wouldn't know if it came from a Steam copy with cloud backups or a GOG copy without cloud backups

It is a very minor and niche issue, not many people have multiple copies of the same games on their systems.

**Comment by mtkennerly** [comment]
Great! Could you give this build a try? It should be able to find Death Stranding now: [ludusavi-v0.28.0-post.12+33a71b1-linux.zip](https://github.com/user-attachments/files/19377461/ludusavi-v0.28.0-post.12%2B33a71b1-linux.zip)

In order to share the Flatpak version's config, you can run it like this:

```
RUST_LOG=ludusavi=trace ./ludusavi --config "/home/deck/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi" backup --preview "Death Stranding"
```

> It is a very minor and niche issue, not many people have multiple copies of the same games on their systems.

That's true, but the main issue is that, even with just one copy, Ludusavi may not always know where it came from. Let's say that it took the game install location into account - then:

* I install and play a Steam game that saves in `~/.config/foo` (not clearly tied to Steam or GOG)
* Ludusavi knows that the game is installed in the Steam folder, so it assumes that the save is from Steam and skips it per the cloud setting
* I uninstall the game
* Now Ludusavi can't tell where the save came from anymore, and the cloud setting may not behave as expected

A more effective solution would probably be for Ludusavi to check the Steam API to find out if any cloud saves had been uploaded for the game, but that's also more complex, especially to make it work consistently for each store.

**Comment by pktiuk** [comment]
> Great! Could you give this build a try? It should be able to find Death Stranding now: [ludusavi-v0.28.0-post.12+33a71b1-linux.zip](https://github.com/user-attachments/files/19377461/ludusavi-v0.28.0-post.12%2B33a71b1-linux.zip)

It detected files

```
(130)(deck@steamdeck Downloads)$ RUST_LOG=ludusavi=trace ./ludusavi --config "/home/deck/.var/app/com.github.mtkennerly.ludusavi/config/ludusavi" backup --preview "Death Stranding"
Death Stranding [22.50 MiB] [+]:
  - [+] /home/deck/Games/Heroic/Prefixes/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c/autosave0/checkpoint.dat
  - [+] /home/deck/Games/Heroic/Prefixes/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c/autosave1/checkpoint.dat
  ...
  - [+] /home/deck/Games/Heroic/Prefixes/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c/quicksave7/checkpoint.dat
  - [+] /home/deck/Games/Heroic/Prefixes/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c/quicksave8/checkpoint.dat
  - [+] /home/deck/Games/Heroic/Prefixes/Death Stranding/pfx/drive_c/users/steamuser/AppData/LocalLow/KojimaProductions/DeathStranding/22ef3c83919d4aa7801ddf11dcc5fc7c/quicksave9/checkpoint.dat

Overall:
  Games: 1 [+1]
  Size: 22.50 MiB
  Location: /home/deck/ludusavi-backup
```

[ludusavi_rCURRENT.log](https://github.com/user-attachments/files/19394322/ludusavi_rCURRENT.log)
