### ISSUE TITLE
Proton initialized title files not found when case does not match.

### ISSUE THREAD

**Issue by wtjones** [mtkennerly/ludusavi#55]
I had to modify the manifest make this entry pull in. The reason for the lower cases is due to the fact that the wine prefix was created on install, and the game's installer must have defaulted to create `my games/company of heroes 2` with that casing for no apparent reason.

The PCGamingWiki _could_ be updated, but would still be broken for users that already had a _My Games_ folder for example.

before:
```
<winDocuments>/My Games/Company of Heroes 2/Savegames:
      tags:
        - save
      when:
        - os: windows
```
after:
```
<winDocuments>/my games/company of heroes 2/Savegames:
      tags:
        - save
      when:
        - os: windows
```

![image](https://user-images.githubusercontent.com/1031558/96392866-f9d77600-1182-11eb-8067-3be19d50ad4c.png)
