### ISSUE TITLE
Unable to detect Ubisoft Connect root

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi#76]
ludusavi is unable to detect my save data for `Immortals Fenyx Rising`

From ludusavi-manifest:
```
Immortals Fenyx Rising:
  files:
    <winDocuments>/Immortals Fenyx Rising:
      tags:
        - config
      when:
        - os: windows
    '{{p|ubisoftconnect}}/savegames/<storeUserId>/5405':
      tags:
        - save
      when:
        - os: windows
```

It only detect the config data:
```
PS C:\Users\marcus> ludusavi.exe backup --merge --preview "Immortals Fenyx Rising"
Immortals Fenyx Rising [335.37 KiB]:                                                                                                   1
  - C:/Users/marcus/Documents/Immortals Fenyx Rising/ImmortalsFenyxRising.ini
  - C:/Users/marcus/Documents/Immortals Fenyx Rising/cache/d315de2f3e6e441f95f06b182f057a17.dat
  - C:/Users/marcus/Documents/Immortals Fenyx Rising/image_cache/177b5_IGN_IFR_Friend-referral_main.jpg
  - C:/Users/marcus/Documents/Immortals Fenyx Rising/image_cache/98c7_10185asset-min%20%281%29.jpg
  - C:/Users/marcus/Documents/Immortals Fenyx Rising/image_cache/f4d7b617df3a8559022aa71a1a428477_OfflineConnectNews.jpeg

Overall:
  Games: 1
  Size: 335.37 KiB
  Location: I:/Games/PC
```

Save files present on my local disk:
```
PS C:\Users\marcus> ls 'C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED_USER_ID\5405\'


    Directory: C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED_USER_ID\5405


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/10/2021   3:28 PM          87223 IFR[AutoSave01].save
-a----         8/10/2021   3:30 PM          87271 IFR[ManualSave01].save
-a----         8/10/2021   3:29 PM           6527 IFR[Options].save
```

It seems like the `ubisoftconnect` variable isn't being evaluated properly. More info on Ubisoft Connect install dir [here](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Ubisoft_Connect)

config.yaml:
```
PS C:\Users\marcus> cat C:\Users\marcus\AppData\Roaming\ludusavi\config.yaml
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"2fed2d65b9fcd0def0f3595990cb2378b6642de120c0edd80dc6f044eb0c46cd\""
roots:
  - path: "C:\\Program Files (x86)/Steam"
    store: steam
  - path: "C:\\Program Files (x86)/Origin Games"
    store: origin
  - path: "C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher"
    store: uplay
  - path: "C:\\Program Files (x86)\\GOG Galaxy"
    store: gogGalaxy
  - path: "C:\\Program Files (x86)\\Epic Games\\Launcher"
    store: epic
backup:
  path: "I:\\Games\\PC"
  ignoredGames: []
  merge: true
  filter: {}
restore:
  path: "C:\\Users\\marcus\\ludusavi-backup"
  ignoredGames: []
  redirects: []
customGames: []
```

Not sure if the rename from `Uplay` to `Ubisoft Connect` last year caused this issue
