### ISSUE TITLE
Add option to match more permissively by install directory and aliases

### ISSUE THREAD

**Issue by mtkennerly** [mtkennerly/ludusavi#86]
This would help ease cases like https://github.com/mtkennerly/ludusavi-playnite/issues/29. For example: `ludusavi backup --permissive Overboard!` would try to back up both `Overboard!` (by name) and `Overboard! (2021)` (by install directory).

Known aliases would require an addition to the manifest, like:

```yaml
Overboard! (2021):
  steam:
    id: 1546920
    name: Overboard!
```

```yaml
Overboard! (2021):
  aliases:
    - Overboard!
```
